- imports/api/documents/both/document-methods.js
- imports/api/documents/both/problemCollection.js
- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/new/document-new.html
- imports/ui/components/documents/new/document-new.js
solution: add basic form and validation
> problem: no problem and solution form

- imports/api/documents/both/problemMethods.js
- imports/startup/both/_main.js
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/new/document-new.js
Solution: Fix all import references and allow problems to be inserted into collection #8
> Problem: Uncaught TypeError: addProblem.call is not a function

- README.md
solution: should be pulling from git://github.com/emurgoHK/emurgis not git://github.com/emurgo/emurgis #10
> problem: typo in README causing issues in pull requests

- .meteor/packages
- .meteor/versions
- imports/api/user/server/accounts-config.js
- imports/startup/client/router/filter-config.js
- imports/startup/server/register-api.js
- imports/ui/shared/header/header.html
- package-lock.json
- package.json
Solution: Implemented an auth system using the accounts, added regex validation for non emurgo.io accounts
> Problem: no auth system #11

- .meteor/packages
- .meteor/versions
solution: add mongol to view mongo collections
> problem: hard to view mongo collections

- imports/ui/components/documents/new/document-new.html
solution: move summary field to end of form
> problem: problem summary field looks weird

- .meteor/packages
- imports/api/user/server/accounts-config.js
Solution: installed and configured accounts-google package. using regex
to validate @emurg.io accounts
> Problem: bad login user experience #23

- imports/api/user/server/accounts-config.js
Solution: Allow users with without @emurgo.io accounts to login in
development
> Problem: none @emurgo.io accounts can't login #28

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
solution: Add a claim button to enable users to claim a problem #31
> problem: users cannot claim issues

- .meteor/versions
- imports/api/documents/both/problemMethods.js
- imports/modules/helpers.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/helpers/handlebars-helpers.js
solution: update [\:problem] view to include who claimed the problem and its claimed status #37
> Problem: Unable to view who claimed an issue

- imports/api/documents/both/problemMethods.js
- imports/startup/client/router/document-routes.js
- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
Solution: Created edit route and added user  to edit a problem
> Problem: [/documentEdit] Problems not editable #30

- imports/startup/client/router/auth-routes.js
- imports/startup/client/router/filter-config.js
- imports/startup/client/router/router.js
- imports/ui/components/auth/signin/signin.html
- imports/ui/components/auth/signin/signin.js
- imports/ui/components/auth/signup/signup.html
- imports/ui/components/auth/signup/signup.js
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/shared/header/header.html
Solution: The page should redirect to login if the user is signed out.
> Problem: no redirect to login if user clicks on add problem #26

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/new/document-new.js
Solution: replaced false description key with solution key and value in insert method. added deleted claimProblem method
> Problem: description no longer added to collection #46

- .travis.yml
- package.json
Solution: Implement Travis CI for unit tests.
> Problem: No CI test framework (#38)

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
solution: add ability to unclaim an issue if you were the user who claimed the issue, show as claimed for other users #36
> Problem: unable to unclaim an issue

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
Solution: Allow users to delete the problems
> Problem: Nothing happens when delete button is clicked #51

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/show/document-show.html
Solution: Adds name in claimProblem method
> Problem: name of user absent in claimed message #58

- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/new/document-new.html
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
Solution: Created isProblemOwner global helper. Added edit button to details page
> problem: users cannot edit problems from the problem detail page #63

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
Solution: Move actions to details page
> Problem: users can claim & unclaim issues from home route #61

- imports/ui/components/documents/show/document-show.html
Solution: Added solution to problem detail page
> problem: solution field is not displayed #60

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/api/utilities.js
- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- package-lock.json
- package.json
Solution:  Added markAsResolved method. Allowing only users who have
claimed problem to mark it as resolved. markAsResolvedTests
> Problem: Users cannot mark problem as resolved #72

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
Solution: added status of in-progress/open when problem is claimed/unclaimed. Testing the claim and unclaim methods
> Problem: claimed problems not marked as in progress #79

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/index/documents-index.html
Solution: Adds status, improves the date & removes extra information
> Problem: home route layout isn't very good #84

- .meteor/versions
- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/ui/components/documents/show/document-show.js
Solution: Adds test for methods in problemMethods
> Problem: missing tests for methods in problemMethods #82

- .meteor/versions
- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/show/document-show.js
Solution: set status of problem in claimProblem & unclaimProblem methods
> problem: problems not marked as "in progress" once claimed #92

- .travis.yml
- wdio.conf.js
Solution: Setup and run WDIO client side tests in Travis CI environment.
> Problem: No client side tests (#93)

- imports/startup/client/_main.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/shared/problemForm.js
solution: added live checks for problem inputs. disabligng keypress events when number of characters exceed max threshold count
> problem: no live checking for field lengths #83

- imports/ui/components/documents/show/document-show.html
solution: remove extra claim button #104
> problem: extra claimed tag on problem detail page

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.html
solution: create helper to lookup users name by ID and add on problem page #90
> problem: created by names are not shown on problems

- imports/api/documents/both/problemMethods.test.js
- imports/ui/stylesheets/bundle.scss
- package-lock.json
- package.json
solution: installed CoreUI theme, imported CoreUi styles and components. Fixed failing test
> problem: CoreUI not used #87

- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/stats/userStats.js
Solution: Adds same colors for tags for home & problem details
> problem:colours for tags on problem page do not match home route #103

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
solution: setting resolved to true and adding resolved details when problem is marked as closed
> problem: problem detail page doesn't show who resolved it #100

- imports/api/documents/both/problemMethods.js
solution: Update var to query profile.name instead of just name. #101
> problem:problem detail page does not show who claimed an issue

- imports/api/documents/both/problemMethods.js
solution: increment completedBy when status is changed #105
> problem:no statistic for problems that users have completed

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
solution: add checkboxes to to filter on the problem status #118
> problem:unable to filter problems

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.js
solution: update closed text to be "this is fixed/solved" #126
> problem: wording for "closed" is innacurate

- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-comments.html
- package-lock.json
- package.json
solution: add markdown npm package.. everyone loves markdown #132
> problem: line breaks created by return key do not show on text

- imports/ui/components/documents/show/document-show.js
- package-lock.json
- package.json
solution: implement sweetalerts instead #138
> problem: browser dialogues in use

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/index/documents-index.html
solution: add count of comments on index page #134
> problem: no count of comments on index

- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
solution: display inline error text when comment is empty, too small or too lengthy
> problem: it's possible to add empty comments #141

- imports/api/documents/both/problemMethods.js
- imports/api/stats/both/statsCollection.js
- imports/startup/client/router/stats-routes.js
- imports/ui/components/stats/userStats.html
- imports/ui/components/stats/userStats.js
Solution: Modify the current stats page to show stats of all users. Display current user's stats as the first element of the table.
> Problem: No page to compare performance of all users (#106)

- imports/ui/components/documents/show/document-show.html
Solution: Cleans up the UI of details page
> Problem: problem and solution text is not well delineated #133

- client/head.html
- imports/startup/client/_main.js
- imports/startup/client/router/document-routes.js
- imports/startup/client/router/group-config.js
- imports/startup/client/router/notifications-routes.js
- imports/startup/client/router/stats-routes.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index.html
- imports/ui/layouts/layout.html
- imports/ui/layouts/layout.scss
- imports/ui/shared/breadcrumb/breadcrumb.html
- imports/ui/shared/breadcrumb/breadcrumb.js
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Changed Emurgis layout. Added a breadcrumb section and sidenav
> Problem: CoreUI theme not taken full advantage of #115

- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/commentsMethods.test.js
- imports/startup/client/router/document-routes.js
- imports/ui/components/documents/show/document-comments.html
- imports/ui/components/documents/show/document-comments.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.scss
solution: added a settings icon on comment with delete action. added tests for comment delete methods
> problem: users cannot delete their comments #149

- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/commentsMethods.test.js
- imports/ui/components/documents/show/document-comments.html
- imports/ui/components/documents/show/document-comments.js
Solution: Implement a way for users to quickly edit their comments on the problems page.
> Problem: Users cannot edit their comments (#150)

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/show/document-show.html
Solution: If the problem is owned by the currently logged in user, show a tag on the problem page, and let users filter out problems created by them.
> Problem: No tag for self-owned issues (#135)

- imports/ui/components/documents/show/document-show.js
Solution: Change button text to "{{username}} has solved this issue" and only display it only after an issue has been tagged as "ready for review".
> Problem: Users can close problems that aren't resolved (#122)

- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.scss
Solution: added an action button area in the bottom of page and adjusted the rest of the buttons and labels in problem detail section
> Problem: problem detail button layout hard to use #121

- imports/ui/components/documents/index/documents-index.html
solution: remove checkbox filter of resolved #127
> problem: resolved is not obsolete

- imports/ui/components/documents/show/document-show.html
solution: remove a white space :( #168
> problem: solution text not displaying

- imports/ui/components/documents/show/document-show.js
Solution: made it green by changing bootstrap class
> problem: 'I have solved problem' button doesn't standout #166

- imports/ui/shared/header/header.html
solution: add notification icon in the navbar #120
> problem:notifications are not obvious

- imports/startup/client/config.js
- imports/startup/client/router/group-config.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/header/header.scss
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
- imports/ui/shared/sidebar/sidebar.scss
solution: added sidebar open, close and compact functionalities
> problem: users cannot toggle sidebar #153

- imports/modules/helpers.js
- imports/ui/components/stats/userStats.html
- imports/ui/helpers/handlebars-helpers.js
solution: deduct abandoned count from totally claimed count to display as claimed problems
> problem: [/stats] wrong claimed numbers #176

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/components/documents/show/resolved-modal.html
- imports/ui/components/documents/show/resolved-modal.js
Solution: displaying modal when users marks problem as resolved. Showing the submited solution for a problem that has been marked as resolved
> problem: users cannot provide summary of how they solved a problem #125

- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/shared/problemForm.js
solution: increased problem solution summary  character limit by 10
> problem: problem summary field too short #178

- imports/startup/client/router/document-routes.js
- imports/startup/client/router/notifications-routes.js
- imports/ui/components/documents/index/documents-claimed.html
- imports/ui/components/documents/index/documents-claimed.js
- imports/ui/shared/sidebar/sidebar.html
Solution: Add a new view (`/claimed`) where users can see all problems they've claimed.
> Problem: Users can't list all problems they have claimed (#183)

- imports/ui/shared/sidebar/sidebar.html
Solution: Add a new problem button to the sidebar.
> Problem: No "new problem" button in sidebar (#182)

- client/head.html
Solution: Load fontawesome 5.0.11 from CDN.
> Problem: Unable to select icons when doing frontend UX (#144)

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
solution: added an isProblemWithEmurgis boolean field to distinguish between emurgis and non-emurgis issues
> problem: cannot log issues for Emurgis itself #139

- imports/ui/components/documents/shared/problemForm.js
- imports/ui/components/documents/show/document-show.js
solution: doubled the max allowed characters for problem, solution and comments
> problem: field lengths are too short #190

- imports/ui/layouts/layout.html
solution: deleted unncessary breadcrumb
> problem: unnecessary breadcrumb bar #181

- imports/ui/components/notifications/notifications.js
solution: mark as read only when clicked on notification
> problem: can't tell which notifications read #191

- imports/startup/client/router/document-routes.js
- imports/ui/components/documents/index/documents-logged.html
- imports/ui/components/documents/index/documents-logged.js
- imports/ui/shared/sidebar/sidebar.html
solution: added a my-logged-problems view for user's own logged issues - added link to sidebar
> problem: users cannot easily see their own logged problems #192

- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/problemMethods.js
solution: changed validations to allow up to 1000 characters for problem and solution while 500 characters for comment
> problem: incorrect validation of field lengths #204

- imports/api/documents/both/.#problemMethods_LOCAL_37007.js
- imports/api/documents/both/.#problemMethods_LOCAL_37140.js
- imports/api/documents/both/.#problemMethods_REMOTE_37007.js
- imports/api/documents/both/.#problemMethods_REMOTE_37140.js
- imports/api/documents/both/dependenciesCollection.js
- imports/api/documents/both/dependenciesMethods.js
- imports/api/documents/both/dependendiesMethods.test.js
- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/new/document-new.html
- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/shared/problemForm.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
Solution: Adds dependencies to problem in the app
> Problem: users cannot add dependencies #33

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
solution: add search bar searching all fields of a problem on the problem index page #193
> problem: no full text search

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
solution: add ability to unsolve a problem once marked as solved. Tracking the history of this so we can be aware if problems are marked as unresolved often by certain users #213
> problem: users cannot "un-solve" problems

- .meteor/versions
- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
solution: create estimate field on show,edit,add problem functionality #215
>  problem: no time estimates

- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
solution: moved solved button inside submitted solution card and changed button text and background color to success
> problem: "xxxx has solved this problem" button in wrong location #194

- imports/ui/components/stats/userStats.html
- imports/ui/components/stats/userStats.js
- package-lock.json
- package.json
Solution: Show a bar chart with a number of completed problems for each user on the top of the stats page.
> Problem: No solved problems graph (#205)

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- package-lock.json
solution: added remove claimer button and corresponding methods. updated tests
> problem: owners cannot kick claimers #196

- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
Solution: Allow users to remove dependencies both when adding a problem and on the problem page.
> Problem: Cannot un-link dependencies (#211)

- imports/api/documents/both/problemMethods.js
- imports/modules/helpers.js
- imports/startup/client/router/document-routes.js
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/index/documents-logged.html
- imports/ui/components/documents/index/documents-logged.js
- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/components/documents/show/reject-modal.html
- imports/ui/components/documents/show/reject-modal.js
- imports/ui/components/stats/userStats.html
- imports/ui/shared/sidebar/sidebar.html
Solution: Prompt moderators for a reason when they are deleting a problem and add this reason as a comment with a red background on the problem page. Then, remove the problem from home index, but keep it on user's logged problems page so users can see what they did wrong. Add a new sidebar button for `rejected problems`.
> Problem: When maintainers delete a problem no record is kept (#220)

- imports/ui/components/documents/shared/problemForm.js
Solution: Update searching algorithm so it'll match all problems with summaries/descriptions that contain any of the search words.
> Problem: Searching box for adding dependencies only searches left to right (#222)

- imports/startup/client/router/document-routes.js
- imports/ui/components/documents/index/documents-resolved.html
- imports/ui/components/documents/index/documents-resolved.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: Add a notification icon in the menu bar with a label showing the number of problems owned by this users that are marked as "ready for review". When clicked, go to a view (`/resolved`) that shows these problems.
> Problem: Users not acting problems that are ready for review (#223)

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
Solution: Fix the `Emurgis` checkbox.
> Problem: "Emurgis" checkbox doesn't work (#235)

- imports/api/documents/both/problemMethods.js
Solution: If the problem's owner solved the problem then accept the solution immediately and mark the problem as 'closed/fixed'.
> Problem: When owners solve a problem a review is required (#233)

- imports/ui/components/documents/new/document-new.html
- imports/ui/components/documents/shared/problemForm.js
Solution: Changing form title and form background color to blue when problemWithEmurgis is checked
> Problem: some users are accidentally making Emurgis problems #242

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
Solution: Grey out problems in the list view that have any dependencies that are not fixed/solved.
> Problem: Problems with unmet dependencies not greyed out. (#249)

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
solution: moved search bar to top navbar
> problem: search bar in bad position #232

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/new/document-new.html
- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/shared/problemForm.js
Solution: Let users add dependencies in both directions when adding new problems or editing existing ones.
> Problem: Can't add dependency from sub-problem (#248)

- .meteor/packages
- .meteor/versions
- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/problemMethods.js
- imports/api/uploader/imageUploader.js
- imports/api/uploader/mimeType.js
- imports/startup/server/register-api.js
- imports/ui/components/documents/edit/document-edit.html
- imports/ui/components/documents/edit/document-edit.js
- imports/ui/components/documents/new/document-new.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/shared/problemForm.js
- imports/ui/components/documents/show/document-comments.html
- imports/ui/components/documents/show/document-comments.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/components/uploader/imageUploader.html
- imports/ui/components/uploader/imageUploader.js
- package-lock.json
- package.json
Solution: Create a reusable image uploader component and let users upload images with comments and problems.
> Problem: Cannot upload images (#247)

- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/shared/header/header.js
Solution: When using the search bar, query all comments on a problem as well to see if there's a match.
> Problem: Search bar doesn't search comments (#257)

- imports/ui/shared/header/header.html
- package-lock.json
Solution: the count is only shown if the count is > 0
> Problem: bad UX of notifications on nav bar #262

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/shared/problemForm.html
Solution: Adds validation for estimate field
> Problem: user able to enter negative estimate in /new #265

- imports/api/documents/both/problemMethods.js
- imports/api/user/both/userMethods.js
- imports/api/user/server/accounts-config.js
- imports/startup/server/register-api.js
- imports/ui/components/documents/index/tests/documents-index.ui-test.js
- imports/ui/components/documents/new/tests/documents-new.ui-test.js
- imports/ui/components/documents/show/tests/document-show.ui-test.js
- imports/ui/components/stats/userStats.ui-test.js
- imports/ui/shared/header/header.ui-test.js
Solution: Add extensive new UI tests (WDIO + Mocha) for the following pages: `problems`, `new problem`, `problem`, `stats`, `header`.
> Problem: No client side tests in the app (#110)

- .meteor/versions
- imports/api/notifications/both/notificationsCollection.test.js
- imports/api/notifications/both/notificationsMethods.js
- imports/ui/components/notifications/notifications.html
- imports/ui/components/notifications/notifications.js
solution: adds a button to mark all as read
> problem: cannot mark all notifications as read #270

- AUTHORS.md
- README.md
Solution: Removed obsolete Mongo part from the readme and additionally added AUTHORS.md file. Please add your name to it if you are a contributor.
> Problem: command to insert in mongo is throwing an error #261

- imports/ui/shared/header/header.html
Solution: removes redundant options in user dropdown
> Problem: redundant options in user dropdown #275

- imports/api/documents/both/problemMethods.test.js
> Problem: Tests are failing (#272)

- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
Solution: Adds a list of problems that are blocked by the issue
> Problem: can't see which problems a problem is blocking #279

- imports/startup/client/router/profile-routes.js
- imports/startup/client/router/router.js
- imports/ui/components/documents/show/document-comments.html
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/profile/userProfile.html
- imports/ui/components/profile/userProfile.js
- imports/ui/shared/header/header.html
Solution: Adds a user profile page with activity details
@gazhayes Please check this layout. Do let me know if you want me to add something here.
> problem: no user profile page to see other user's details #280

- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/sidebar/sidebar.js
- package-lock.json
solution: make Emurgis reactive and offer a better UX on smaller screens #288
> problem: layout isnt very good on small screens

- imports/api/documents/both/dependendiesMethods.test.js
Solution: Adds test for circular dependencies
> Problem: missing test for checking circular dependencies #293

- imports/ui/shared/header/header.scss
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.scss
Solution: Aligned logo to the left side.
Additionally fixed sidebar line breaking. Now everything in sidebar is in one line
> Problem: header layout is weird #295

- imports/api/documents/both/problemMethods.js
- imports/ui/components/profile/userProfile.html
- imports/ui/components/stats/userStats.html
- imports/ui/components/stats/userStats.js
Solution: Fixes the logic for user stats
> Problem: discrepancy between completed problems  #296

- README.md
- imports/startup/client/accounts.js
Solution: Updated readme.md with proper steps for authentication
> Problem: Documentation needs to be updated #300

- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
solution: remove double dependency text in documents-show and problemForm views
> problem: double text on new problem page #306

- imports/ui/components/documents/shared/problemForm.html
solution: removed estimate workload from newProblem from
> problem: estimate workload is asked on the new problem page #305

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/show/document-show.html
solution: Adds user stat updation when problem is deleted
> problem: discrepancy between completed & actual completed problems #296

- imports/ui/components/documents/shared/problemForm.html
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
solution: updated estimate label texts and placeholder
> problem: not clear what time estimates are #304

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
Solution: removed background and added the ban icon with a class of text-danger
> Problem: bad background color for dependent problems #301

- imports/ui/components/profile/userProfile.html
Solution: Replaced problemId with _id on issue item link
> Problem: links on user profile page not redirecting to issue #308

- imports/ui/components/documents/shared/problemForm.html
Solution: applied same style as that used in problem show page
> Problem: bad ui for dependencies on new problem form #303

- imports/api/documents/both/problemMethods.js
- imports/ui/components/documents/index/tests/documents-index.ui-test.js
- imports/ui/components/documents/new/tests/documents-new.ui-test.js
- imports/ui/components/documents/show/tests/document-show.ui-test.js
- imports/ui/components/notifications/notifications.ui-test.js
- imports/ui/components/stats/userStats.ui-test.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.ui-test.js
Solution: Fix failing tests and remove testing data after tests are complete.
> Problem: Tests are broken (#319)

- imports/api/user/both/userMethods.js
- imports/ui/components/documents/index/documents-dobModal.html
- imports/ui/components/documents/index/documents-dobModal.js
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
solution: display a modal when the user signs and prompts to provide a DOB; once provided the modal does not display #312
> problem: user date of birth not tracked

- imports/api/user/both/userMethods.js
- imports/ui/components/documents/show/document-show.js
Solution: Show a message with calculated value of users time when user is
entering a time estimate for problem solution.
> Problem: Value of user's time is not apparent (#324)

- imports/ui/components/documents/index/documents-index.js
- wdio.conf.js
Solution: checking if user has a profile key
> Problem: Navigating to home throws TypeError #326

- .meteor/packages
- .meteor/versions
- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/dependenciesMethods.js
- imports/api/documents/both/problemCron.js
- imports/api/documents/both/problemMethods.js
- imports/startup/server/_main.js
- imports/startup/server/register-api.js
- imports/startup/server/startup.js
- imports/ui/components/documents/index/documents-claimed.html
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-logged.html
- imports/ui/components/documents/shared/problem-helpers.js
- wdio.conf.js
Solution: Add a cron job every day that'll check for stale problems and mark them accordingly. A problem is considered stale if it hadn't had any activity in the last 10 days. If the problem is marked as stale, notify
the author. Also, implement logic that will return the problem to its old status if it gets some activity after being marked as stale.
> Problem: Problems not marked as stale (#328)

- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/problemMethods.js
- imports/api/user/both/userMethods.js
- imports/api/user/server/publications.js
- imports/startup/client/router/profile-routes.js
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/components/profile/usernameModal.html
- imports/ui/components/profile/usernameModal.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: Adds feature to add tags & tag other users in comments
> Problem: can't ping other users #307

- imports/startup/server/accounts.js
- settings.json
solution: DO NOT PURGE OAUTH CREDENTIALS!
> problem: auth system is broken (regression)

- imports/startup/server/_main.js
solution: remove startup imports that no longer exist
> problem: build is failing

- .travis.yml
- imports/api/notifications/both/notificationsMethods.js
- imports/api/uploader/imageUploader.test.js
- imports/ui/components/documents/index/tests/documents-index.ui-test.js
- imports/ui/components/notifications/notifications.ui-test.js
- imports/ui/components/stats/userStats.ui-test.js
- imports/ui/components/uploader/imageUploader.ui-test.js
Solution: Add new server side and client side tests for stats and image uploader API. Update client side tests for documents and notifications with pub/sub tests.
> Problem: No tests for stats-uploader APIs (#335)

- imports/ui/components/documents/show/document-show.js
Solution: Implement correct error handling in the problem claiming process.
> Problem: No error thrown when time estimate fails (#337)

- .meteor/packages
- .meteor/versions
- imports/startup/server/_main.js
- imports/startup/server/rest-api.js
- package-lock.json
- wdio.conf.js
solution: installed restivus package and added get and getAll endpoints for the Problems collection
> problem: no API to fetch issues #343

- imports/ui/components/profile/usernameModal.html
solution: added text describing the purpose of the add username modal
> problem: not clear what add username modal is for #347

- .meteor/packages
- .meteor/versions
- imports/api/user/both/userStatsCollection.js
- imports/api/user/server/publications.js
- imports/startup/both/_main.js
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
- imports/ui/shared/sidebar/sidebar.ui-test.js
Solution: Add a "users online" box in the side menu and list the currently connected users.
> Problem: Can't see which users are online (#346)

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
Solution: Notify all users when there's a new FYI issue and add appropriate tests.
> Problem: Users not notified when there's a new FYI issue (#354)

- README.md
Solution : Fixed the file name/path
> Problem : AUTHORS file link is broken #358

- imports/api/documents/both/problemMethods.js
- imports/api/documents/both/problemMethods.test.js
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/components/documents/show/reopen-problem-modal.html
- imports/ui/components/documents/show/reopen-problem-modal.js
Solution: Allow anyone to reopen a closed issue and transfer ownership to that user. Show all previously accepted solutions with a reason why the solution wasn't good.
> Problem: Cannot re-open closed issues (#361)

- imports/api/documents/both/commentsMethods.js
- imports/api/notifications/both/notificationsCollection.js
- imports/api/notifications/both/notificationsMethods.js
- imports/startup/client/router/notifications-routes.js
- imports/ui/components/documents/show/tests/document-show.ui-test.js
- imports/ui/components/mentions/mentions.html
- imports/ui/components/mentions/mentions.js
- imports/ui/components/mentions/mentions.ui-test.js
- imports/ui/components/notifications/notifications.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: Add a new mentions page where users can see where they've been mentioned. Include the mentions count in the header.
> Problem: No mentions tab (#363)

- imports/api/documents/both/commentsMethods.js
- imports/modules/helpers.js
- imports/ui/components/documents/show/comment-likes.html
- imports/ui/components/documents/show/comment-likes.js
- imports/ui/components/documents/show/document-comments.html
- imports/ui/components/documents/show/document-comments.js
- imports/ui/components/documents/show/document-comments.scss
- imports/ui/components/documents/show/document-show.html
- imports/ui/components/documents/show/document-show.js
- imports/ui/helpers/handlebars-helpers.js
- package-lock.json
- package.json
Solution: added a thumbs up button which likes/unlikes comment when clicked. created  comment likes modal that displays a list of users who liked comment.
> Problem: cannot like comments #364

- imports/api/documents/both/commentsMethods.js
- package-lock.json
Solution: user must be notified only once for a single action. Remove multiple notifications & implement single notification of an action
> Problem: user notified multiple times for action on problem #372

- imports/ui/components/documents/shared/problem-helpers.js
- imports/ui/components/documents/show/document-show.js
Solution: user must only be allowed to mark a problem as solved if the dependencies have been resolved.
> Problem: user can mark problem as solved if dependency is unsolved #374

- imports/api/user/both/userMethods.test.js
Solution: Add server side tests for user API.
> Problem: No tests for user api (#332)

- imports/ui/shared/header/header.html
- package-lock.json
solution: lower width of search bar and hide one element when in mobile mode. Suggest is to move the search bar to a modal instead of in the header.
> problem: header is too long for mobile #383

- imports/ui/components/documents/shared/problemForm.js
Solution: Adds search for only active problems with status 'open', 'in progress', or 'ready for review'
> problem:when adding dependency or parent closed issues are searched #386

- imports/ui/components/stats/userStats.html
solution: add cards to stats instead of table for mobile only #382
> problem: stats page is not responsive

- imports/ui/components/stats/userStats.ui-test.js
- package-lock.json
Solution: Fix broken UI tests.
> Problem: Tests are broken (#385)

- imports/ui/components/documents/index/documents-claimed.html
- imports/ui/components/documents/index/documents-claimed.js
- imports/ui/components/documents/index/documents-index.html
- imports/ui/components/documents/index/documents-index.js
- imports/ui/components/documents/index/documents-logged.html
- imports/ui/components/documents/index/documents-logged.js
solution: enable the stale checkbox by default
> problem: stale issues not displayed by default #402

- imports/ui/components/documents/shared/problem-helpers.js
Solution: Properly handle the edge case when there's no problem with provided id.
> Problem: Exception in template helper 'getSummaryById' (#400)

- imports/api/documents/both/problemMethods.js
- package-lock.json
solution: if a problem is ready for review, never mark it as stale.
> problem: problems that are ready for review are marked as stale #406

- imports/ui/components/documents/show/document-show.html
- imports/ui/stylesheets/common.scss
Solution: properly align the buttons for small screen
> Problem: edit & delete buttons overflow the parent on problems page #379

- imports/ui/components/notifications/notifications.html
Solution: Set responsive design to the page
> Problem: content overflowing on notifications page for small screen #380

- imports/ui/components/notifications/notifications.ui-test.js
Solution: Fix client side tests.
> Problem: Tests are failing (#415)

- AUTHORS.md
solution: add name to AUTHORS file
> problem: name not in AUTHORS file

- MAINTAINERS.MD
Solution: list the maintainers
> Problem: maintainers are not listed

- imports/ui/components/mentions/mentions.html
- imports/ui/components/mentions/mentions.ui-test.js
- imports/ui/stylesheets/common.scss
Solution: set responsive design
> Problem: content overflowing on mentions page in small screens #381

- .travis.yml
- imports/api/uploader/imageUploader.js
- imports/api/uploader/imageUploader.test.js
solution: move upload dir to home directory
> problem: upload dir not writable by user

- imports/ui/components/stats/userStats.html
Solution: Set Table Desktop/Large screen
> Problem: State Table is not in proper UI/View in Desktop view #401

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
Solution: Set all header elements with proper space
> Problem: Header right elements not align properly with space #397

- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/problemMethods.js
- imports/startup/server/startup.js
Solution: Create helper methods to convert old image URLs to new ones and call them on startup.
> Problem: Incorrect image url (#420)

- imports/ui/components/stats/userStats.html
> Problem: Statistics state table content overlaying in small screen #390

- imports/ui/components/profile/userProfile.html
- imports/ui/stylesheets/common.scss
Solution: Set responsive view for profile page
> Problem: Profile activity tabs are not aligned in small screen #392

- imports/ui/shared/sidebar/sidebar.html
- imports/ui/stylesheets/common.scss
Solution: Set max height and scroll in responsive as well
> Problem: [Side menu] Online user section overlap menu items #431

- imports/startup/client/config.js
Solutoin: On Small screen page load sid menu set hidden
> Problem: [Small screen] On page load side menu is not hidden #430

- AUTHORS
solution: added Sam's name to authors list
> problem: not all authors are in the authors file #435

- AUTHORS
- package-lock.json
Solution : Own name added in authors file
> Problem: Names isn't in the authors file #435

- imports/api/user/both/userMethods.js
- imports/startup/client/router/profile-routes.js
- imports/ui/components/profile/editProfile.html
- imports/ui/components/profile/editProfile.js
- imports/ui/shared/header/header.html
Solution : Edit profile page added where user can update name and email
>  Problem : Edit user profile not available #441

- imports/ui/components/profile/signInModal.html
- imports/ui/components/profile/signInModal.js
Solution : Name, DOB and User Name added in signup form
> Problem : Signup page content and UX #444

- .travis.yml
- imports/api/documents/both/commentsMethods.js
- imports/api/documents/both/problemMethods.js
- imports/api/uploader/imageUploader.js
- imports/api/uploader/imageUploader.test.js
Solution: Update paths in the codebase, fix tests and fix `fixProblemImages` and `fixCommentImages` methods to convert old paths to new paths.
> Problem: Image upload directory has changed (#439)

- imports/ui/stylesheets/bootstrap/_bootstrap.scss
- imports/ui/stylesheets/bundle.scss
- imports/ui/stylesheets/theme/core_ui_variables.scss
- package-lock.json
- package.json
solution: updated bootstrap and webdriverio package dependencies. fixed broken stylesheets
> problem: some dependencies have security issues #447

- imports/ui/components/documents/index/documents-index-item/documents-index-item.html
- imports/ui/components/documents/index/documents-index-item/documents-index-item.js
- imports/ui/components/documents/index/documents-logged.html
- package-lock.json
Solution : Table layout overlapping on smaller screens updated
> Problem: Table view are overlaying #391

- README.md
solution: Add a reminder in Readme.
> problem: Reminder missing
